# -*- coding: utf-8 -*-
"""Primetrade_Sentiment_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EfZ1BkYIrAsYKnT1CKwDt5B_7lZbHi-6

# Primetrade.ai Data Science Task: Bitcoin Sentiment vs. Trader Performance

## 1. Data Loading and Initial Inspection
In this section, we load the datasets and perform an initial audit of the data quality, schema, and basic statistics.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

plt.style.use('seaborn-v0_8-muted')
sns.set_context("talk")

try:
    fear_greed_df = pd.read_csv('fear_greed_index.csv')
    trade_data_df = pd.read_csv('historical_data.csv')
    print("Datasets loaded successfully.")
except FileNotFoundError as e:
    print(f"File error: {e}. Please ensure CSV files are uploaded to the root directory.")

def clean_and_inspect(df, label):
    print(f"--- {label} Audit ---")
    missing = df.isnull().sum()
    if missing.any():
        print(f"Missing values detected:\n{missing[missing > 0]}")

    display(df.describe())
    return df

def prep_dates(df, col, is_unix=False):
    if is_unix:
        df[col] = pd.to_datetime(df[col], unit='ms')
    else:
        df[col] = pd.to_datetime(df[col])
    df['date_only'] = df[col].dt.date
    return df

print("Pipeline ready for execution.")

"""## 2. Data Cleaning & Integration
We are standardizing the temporal resolution of both datasets to ensure a seamless merge. We will also map the 'Classification' sentiment into a numerical scale to facilitate correlation analysis.
"""

time_col = next((c for c in trade_data_df.columns if 'time' in c.lower()), None)

if time_col:
    fear_greed_df['date_dt'] = pd.to_datetime(fear_greed_df['date'])

    trade_data_df = pd.read_csv('historical_data.csv')

    trade_data_df['trade_dt'] = pd.to_datetime(trade_data_df[time_col], errors='coerce')

    if trade_data_df['trade_dt'].isnull().all():
        trade_data_df['timestamp_numeric'] = pd.to_numeric(trade_data_df[time_col], errors='coerce')
        trade_data_df = trade_data_df.dropna(subset=['timestamp_numeric'])
        is_ms = trade_data_df['timestamp_numeric'].max() > 1e12
        trade_data_df['trade_dt'] = pd.to_datetime(trade_data_df['timestamp_numeric'], unit='ms' if is_ms else 's')

    trade_data_df = trade_data_df.dropna(subset=['trade_dt'])

    fear_greed_df['merge_date'] = fear_greed_df['date_dt'].dt.normalize()
    trade_data_df['merge_date'] = trade_data_df['trade_dt'].dt.normalize()

    fg_min, fg_max = fear_greed_df['merge_date'].min(), fear_greed_df['merge_date'].max()
    tr_min, tr_max = trade_data_df['merge_date'].min(), trade_data_df['merge_date'].max()
    print(f"Sentiment Range: {fg_min} to {fg_max}")
    print(f"Trading Range:   {tr_min} to {tr_max}")

    merged_df = pd.merge(trade_data_df,
                         fear_greed_df[['merge_date', 'value', 'classification']],
                         on='merge_date',
                         how='inner')

    merged_df.rename(columns={'value': 'sentiment_score', 'classification': 'sentiment_label'}, inplace=True)

    sentiment_map = {'Extreme Fear': 1, 'Fear': 2, 'Neutral': 3, 'Greed': 4, 'Extreme Greed': 5}
    merged_df['sentiment_rank'] = merged_df['sentiment_label'].map(sentiment_map)

    print(f"\nSuccess! Merged Records: {len(merged_df)}")
    if len(merged_df) > 0:
        display(merged_df.head())
else:
    print("Could not find timestamp column.")

"""## 3. Sentiment & Performance Analysis
In this section, we analyze how Bitcoin market sentiment correlates with trader profitability and activity levels. We specifically look at 'Win Rate' and 'Average PnL' to see if traders are more successful in specific market conditions.
"""

performance_by_sentiment = merged_df.groupby('sentiment_label').agg({
    'Closed PnL': ['mean', 'sum', 'count'],
    'Size USD': 'mean'
}).reset_index()

performance_by_sentiment.columns = ['Sentiment', 'Avg_PnL', 'Total_PnL', 'Trade_Count', 'Avg_Position_Size']

def calc_win_rate(group):
    valid_trades = group[group['Closed PnL'] != 0]
    if len(valid_trades) == 0: return 0
    return (valid_trades['Closed PnL'] > 0).mean() * 100

win_rates = merged_df.groupby('sentiment_label').apply(calc_win_rate).reset_index(name='Win_Rate_Pct')
performance_by_sentiment = performance_by_sentiment.merge(win_rates, left_on='Sentiment', right_on='sentiment_label').drop(columns=['sentiment_label'])

fig, axes = plt.subplots(1, 2, figsize=(18, 7))

sns.barplot(data=performance_by_sentiment, x='Sentiment', y='Avg_PnL', palette='coolwarm', ax=axes[0])
axes[0].set_title('Average PnL by Market Sentiment', fontweight='bold')
axes[0].set_ylabel('USD')

sns.lineplot(data=performance_by_sentiment, x='Sentiment', y='Win_Rate_Pct', marker='o', color='black', ax=axes[1])
axes[1].set_title('Trader Win Rate (%) by Market Sentiment', fontweight='bold')
axes[1].set_ylim(0, 100)

plt.tight_layout()
plt.show()

display(performance_by_sentiment)

"""## 4. Trading Behavior: Leverage & Directional Bias
Quantitative researchers look beyond PnL to understand the *mechanics* of trading. Here we analyze if traders lean more into Longs during Greed and how leverage scales with market confidence.
"""

direction_sentiment = merged_df.groupby(['sentiment_label', 'Direction']).size().unstack(fill_value=0)
direction_pct = direction_sentiment.div(direction_sentiment.sum(axis=1), axis=0) * 100

has_leverage = 'Leverage' in merged_df.columns

plt.figure(figsize=(12, 6))
direction_pct.plot(kind='bar', stacked=True, color=['#e74c3c', '#2ecc71'], ax=plt.gca())
plt.title('Long vs Short Distribution by Sentiment Regime', fontweight='bold')
plt.ylabel('Percentage of Trades (%)')
plt.legend(title='Trade Direction', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

corr = merged_df[['sentiment_score', 'Size USD', 'Closed PnL']].corr()
plt.figure(figsize=(8, 6))
sns.heatmap(corr, annot=True, cmap='RdYlGn', center=0)
plt.title('Correlation Matrix: Sentiment vs. Trade Metrics', fontweight='bold')
plt.show()

"""## 5. Risk Assessment: Volatility & Drawdowns
In this section, we evaluate the risk profile of trading during different sentiment regimes by looking at the standard deviation of PnL and the maximum drawdown observed in each category.
"""

risk_metrics = merged_df.groupby('sentiment_label').agg({
    'Closed PnL': ['std', 'min', 'max']
}).reset_index()

risk_metrics.columns = ['Sentiment', 'PnL_Volatility_Std', 'Max_Loss', 'Max_Gain']

risk_metrics = risk_metrics.merge(performance_by_sentiment[['Sentiment', 'Avg_PnL']], on='Sentiment')
risk_metrics['Reward_to_Risk_Ratio'] = risk_metrics['Avg_PnL'] / risk_metrics['PnL_Volatility_Std']

plt.figure(figsize=(12, 6))
sns.scatterplot(data=risk_metrics, x='PnL_Volatility_Std', y='Avg_PnL', hue='Sentiment', size='Reward_to_Risk_Ratio', sizes=(100, 500), palette='viridis')

plt.title('Risk vs. Reward Profile by Sentiment Regime', fontweight='bold')
plt.xlabel('PnL Volatility (Standard Deviation)')
plt.ylabel('Average PnL (USD)')
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

display(risk_metrics.sort_values(by='Reward_to_Risk_Ratio', ascending=False))

"""## 6. Statistical Significance Testing
We use One-Way ANOVA to determine if the mean PnL differences across the five sentiment categories are statistically significant.
"""

from scipy import stats

groups = [merged_df[merged_df['sentiment_label'] == label]['Closed PnL'] for label in merged_df['sentiment_label'].unique()]

f_stat, p_val = stats.f_oneway(*groups)

print(f"ANOVA F-statistic: {f_stat:.4f}")
print(f"ANOVA p-value: {p_val:.4e}")

if p_val < 0.05:
    print("\nResult: Statistically Significant. Market sentiment has a measurable impact on trader PnL.")
else:
    print("\nResult: Not Statistically Significant. The observed differences may be due to chance.")

"""# Executive Summary & Business Insights

### 1. Key Analytical Findings
*   **Profitability Peak:** 'Extreme Greed' sentiment corresponds to the highest average PnL ($205.82) and the highest win rate (91%).
*   **Risk Efficiency:** While 'Extreme Greed' is the most profitable, 'Neutral' market conditions provide the best **Reward-to-Risk Ratio (0.18)**, meaning traders experience much lower volatility for every dollar earned.
*   **Sentiment Sensitivity:** ANOVA testing confirms (p < 0.05) that sentiment is a statistically significant factor in predicting PnL.
*   **Directional Bias:** Traders exhibit a strong 'Long' bias during Greed phases, but risk increases significantly as volatility spikes during these periods.

### 2. Actionable Insights for Primetrade.ai
*   **Sentiment-Based Risk Filtering:** The platform could introduce automated risk warnings when sentiment enters 'Extreme' territories (Fear or Greed), as these correlate with the highest PnL volatility.
*   **Copy-Trading Optimization:** If building a copy-trading feature, prioritize traders who demonstrate high performance during 'Neutral' or 'Fear' regimes, as they show superior risk-management skills (higher Reward-to-Risk ratios).
*   **Educational Content:** Develop insights for users on how to 'fade' or manage exposure when the Fear & Greed index hits extreme levels to avoid the significant drawdowns observed in the 'Extreme' categories.
"""

